name: Firmware build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:

  # normal builds
  build_main:
    runs-on: ubuntu-20.04
    strategy:
      # devices to build for
      matrix:
        board: [NRF52832DK]
      # try and build for all devices even if one fails
      fail-fast: false 
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: make ${{ matrix.board }}
      env:
        TRAVIS: 1
        RELEASE: 1
        BOARD: ${{ matrix.board }} 
        UPLOADTOKEN: ${{ secrets.UPLOADTOKEN }}  
      run: |
        source ./scripts/provision.sh  ${{ matrix.board }}
        make
        ./scripts/ci_upload.sh
    - name: Upload ${{ matrix.board }} build artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: ${{ matrix.board }}
        path: |
          *.bin
          *.hex
          *.tgz
          *.zip
    
# Disable doc building for now 
#  docs:
#    runs-on: ubuntu-20.04      
#    steps:
#    - name: makedocs
#      run: make docs

